### ISSUE TITLE
Build error on Windows - no SlicerDMRI in nightly builds

### ISSUE THREAD

**Issue by lassoan** [SlicerDMRI/SlicerDMRI#121]
SlicerDMRI is not available for Windows in nightly builds due to this error:

    D:\D\P\S-0-E-b\SlicerDMRI\Modules\Loadable\TractIO\TractIOCLI\VTK_to_DICOMTract.cxx(375): error C2039: 'back_inserter': is not a member of 'std' [D:\D\P\S-0-E-b\SlicerDMRI-build\inner-build\Modules\Loadable\TractIO\TractIOCLI\VTK_to_DICOMTractLib.vcxproj] [D:\D\P\S-0-E-b\SlicerDMRI-build\inner.vcxproj]

http://slicer.cdash.org/viewBuildError.php?buildid=1455377

**Comment by ihnorton** [comment]
Thanks
