### ISSUE TITLE
Tube size adjustment

### ISSUE THREAD

**Issue by braincharter** [SlicerDMRI/SlicerDMRI#126]
Hi, great tool! When displaying tracks, I noticed I can't change the diameter of the tube representation (either variable size of fixed size). Maybe I just missed the feature, but if not, it would be a great addition!

**Comment by bartbols** [comment]
I've got the same issue. Has this option been added in the meantime and if so, how can I access it?

**Comment by pieper** [comment]
It's not exposed in the user interface, but you can enter a command like this in the python console:
```
getNode("FiberBundle_F").GetTubeDisplayNode().SetTubeRadius(2)
```
