### ISSUE TITLE
SlicerDMRI build errors with C++17

### ISSUE THREAD

**Issue by jamesobutler** [SlicerDMRI/SlicerDMRI#156]
SlicerDMRI is not building successfully on latest Slicer preview which now sets the minimum standard to C++17 (https://github.com/Slicer/Slicer/commit/dedb6c04d5f987d168e58dfda067717a7039b439).

https://slicer.cdash.org/viewBuildError.php?buildid=2735613
`error C2039: 'random_shuffle': is not a member of 'std'`

> The reason for removing std::random_shuffle in C++17 is that the iterator-only version usually depends on [std::rand](https://en.cppreference.com/w/cpp/numeric/random/rand), which is now also discussed for deprecation. ([std::rand](https://en.cppreference.com/w/cpp/numeric/random/rand) should be replaced with the classes of the [<random>](https://en.cppreference.com/w/cpp/header/random) header, as [std::rand](https://en.cppreference.com/w/cpp/numeric/random/rand) is considered harmful.) In addition, the iterator-only std::random_shuffle version usually depends on a global state. The std::shuffle's shuffle algorithm is the preferred replacement, as it uses a URBG as its 3rd parameter.
[[source](https://en.cppreference.com/w/cpp/algorithm/random_shuffle)]

**Comment by pieper** [comment]
Thanks for the report @jamesobutler 👍 

@ljod @zhangfanmark this should be an easy fix.  Are you abel to do it?  Or I can have a look in a couple weeks.

**Comment by jamesobutler** [comment]
There are no more build errors as of https://github.com/SlicerDMRI/SlicerDMRI/commit/fe29099a449d00e664878cf4457c41f4b83e2cd5.

**Comment by ljod** [comment]
Thank you very much!!
