### ISSUE TITLE
Update modules to use markups instead of annotations

### ISSUE THREAD

**Issue by lassoan** [SlicerDMRI/SlicerDMRI#158]
Annotations module, which provides `vtkMRMLAnnotationROI` and `vtkMRMLAnnotationRuler` nodes have been deprecated since April 2021 and will be removed in Slicer-5.4 stable version early next year.
Since some modules in this extension use annotation nodes, these modules need to be updated to use markups nodes before the end of this year.

[This section](https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide/Slicer#Slicer_5.3%3A_Removed_Annotation_module) of the migration guide should help with implementing the changes and any questions can be asked at the [Remove Annotations module topic in the Slicer forum](https://discourse.slicer.org/t/remove-annotations-module/25271).

Impacted modules:
Modules\Loadable\TractographyDisplay\MRML\vtkMRMLFiberBundleNode.cxx 
Modules\Loadable\TractographyDisplay\Widgets\qSlicerTractographyEditorROIWidget.cxx 
Modules\Loadable\TractographyDisplay\Widgets\Resources\UI\qSlicerTractographyEditorROIWidget.ui

**Comment by lassoan** [comment]
Slicer-5.2 is released. It is the last Slicer Stable Release that contains Annotations module.

We will remove Annotations module from Preview Releases (Slicer-5.3) within a few weeks and from the Stable Release (Slicer-5.4) in about 3-4 months. Your modules need to be updated to use Markups module instead of Annotations to prevent build errors or runtime failures. Let me know if you need any help with this update.

**Comment by pieper** [comment]
Thanks for the update @lassoan, yes, this is on my list to look at when time permits.  It won't happen for several weeks though I'm sure.
