### ISSUE TITLE
Threat detected in SlicerDMRI 

### ISSUE THREAD

**Issue by tbrnd** [SlicerDMRI/SlicerDMRI#167]
Hi everyone,

when installing SlicerDMRI, webroot seems to detect an adware in DIFFUSIONWEIGHTEDVOLUMEMASKING.EXE, here's the output:

```
DIFFUSIONWEIGHTEDVOLUMEMASKING.EXE, W32.Adware.Gen, %appdata%\na-mic\slicer 5.2.1\na-mic\extensions-31317\slicerdmri\lib\slicer-5.2\cli-modules\, https://snup.webrootcloudav.com/SkyStoreFileUploader/upload.aspx?MD5=15F6758593C7D4E7DF7AA1FCC165AB4E 15F6758593C7D4E7DF7AA1FCC165AB4E, 1 sec
```

Setup:
* Slicer 5.2.1
* SlicerDMRI installed from extensions managers, version 344e5f3 (2022-12-22)

At this stage, I'm not sure whether it's a false positive or not, just wanted to let you know.

**Comment by pieper** [comment]
Probably it is a false positive in the virus scanner.  Those pop up from time to time.

The code for that module hasn't changed for several years.
