### ISSUE TITLE
Tests using `FiberBundleFile` data are failing

### ISSUE THREAD

**Issue by jhlegarreta** [SlicerDMRI/SlicerDMRI#207]
All tests using `FiberBundleFile` data, e.g.
https://github.com/SlicerDMRI/SlicerDMRI/blob/372675b96e917acb61bc8cb2ac9262d87cc5b06a/Modules/Loadable/TractographyDisplay/Testing/Python/SlicerMRBTest.py#L75

are failing:
https://slicer.cdash.org/test/25967027

The URLs pointing to invalid addresses has already been identified and an patch set has been submitted:
https://github.com/SlicerDMRI/SlicerDMRI/pull/203

However, even if the data is downloaded correctly after changing the URLs, `FiberBundleFile` data does not get loaded into the scene, and thus querying about the corresponding nodes, e.g. `tract1` fails.

Some more context can be found here:
https://github.com/Slicer/Slicer/issues/7342

**Comment by jhlegarreta** [comment]
The failures in
```
py_TractographyDownsample
py_TractographyExportPLY
```

are ultimately also related to this issue: see https://github.com/SlicerDMRI/SlicerDMRI/issues/205#issuecomment-1801963273.

**Comment by ljod** [comment]
Hi I ran a test locally and the actual failure for me is this for the FA image and others. Steps to do this are:
1) Download SlicerMRBTest.py from this page.
https://github.com/SlicerDMRI/SlicerDMRI/blob/4c4b00b1ea075393e36adaa387553eea6fbecb16/Modules/Loadable/TractographyDisplay/Testing/Python/SlicerMRBTest.py#L311

2) Run the test in the python interactor similar to this
>>> exec(open("/Users/lj07/Downloads/SlicerMRBTest.py").read())
>>> t = SlicerMRB();
>>> t.setUp(); 
>>> t.runTest();

Then the following errors show up only in the interactor (are not output as a test result). It appears that ALL the downloads are actually failing, as far as I can see. There is not an apparent problem actually loading fiber bundles now, nor is there a problem loading nrrd images (the reported failure error for the above test is actually a failure about a volume node that happens to contain an FA image).


[Python] 	Download failed: HTTP Error 400: BAD REQUEST
[Python] Download failed (attempt 1 of 3)...
[Python] 	Download failed: HTTP Error 400: BAD REQUEST
[Python] Download failed (attempt 2 of 3)...
[Python] 	Download failed: HTTP Error 400: BAD REQUEST
[Python] Download failed (attempt 3 of 3)...

**Comment by ljod** [comment]
@pieper Do you know where the test data is stored now? I ran tests locally in my Slicer and the actual failure is a local download failure. Specifically, we used to download things like this, which now fails and causes the tests to fail:

downloads = (
          ('FA', 'FA.nrrd', 'http://slicer.kitware.com/midas3/download?items=5767', 'VolumeFile'),
          ('tract1', 'tract1.vtk', 'http://slicer.kitware.com/midas3/download?items=5768', 'FiberBundleFile'),
          )

**Comment by pieper** [comment]
Hi @ljod Probably those files have new urls now.  @jcfr do you happen to know if there's an updated location?

If we don't have the files handy I believe we could just update the test with new files.

If we don't have any other convenient spot putting them up as release assets in github would be an option.

**Comment by jhlegarreta** [comment]
PR #228 should fix the issue with the URL. I had this PR in my backlog and at the time I had committed it, other issues were preventing tests from passing. Now, it may well be that PR #208 solves such issues. Locally testing `py_fiber_visibility_crash2438` and `py_SlicerMRBTest`, they pass now; `py_test_tractography_display` still fails, but that is unrelated to the URL issue.
