### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by xixi911** [SlicerDMRI/SlicerDMRI#236]
can not find FindSlicer.cmake, i use cmake build slicer，still cannot find it

CMake Error at CMakeLists.txt:22 (find_package):
  By not providing "FindSlicer.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Slicer", but
  CMake did not find one.

  Could not find a package configuration file provided by "Slicer" with any
  of the following names:

    SlicerConfig.cmake
    slicer-config.cmake

  Add the installation prefix of "Slicer" to CMAKE_PREFIX_PATH or set
  "Slicer_DIR" to a directory containing one of the above files.  If "Slicer"
  provides a separate development package or SDK, be sure it has been
  installed.

![image](https://github.com/SlicerDMRI/SlicerDMRI/assets/38411547/d93048c9-78a6-495e-8acc-2fcd3ace80d7)

**Comment by pieper** [comment]
You need to have built slicer locally and then point cmake to the local build.

https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html#build-an-extension

**Comment by xixi911** [comment]
> You need to have built slicer locally and then point cmake to the local build.
> 
> https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html#build-an-extension
Thank you. I've taken care of that. Now there is a new problem, I want to study the color matching for the Tractography bundle, I look at the source code, the color is converted to 1 component scalar,  I want to know where the colormap is stored.  i cant find it
