### ISSUE TITLE
Remove extra/unused branches

### ISSUE THREAD

**Issue by jcfr** [SlicerDMRI/SlicerDMRI#25]
The following branches which were most likely for sake of experimentation while setting up the initial layout could be removed:
* `ddd`
* `master3`
* `master4`
* `master5`

**Comment by jcfr** [comment]
Cc: @ihnorton

**Comment by ihnorton** [comment]
Done... (not sure why this would matter though)

**Comment by jcfr** [comment]
This is unrelated to [#4131](http://na-mic.org/Mantis/view.php?id=4131). 

No changes in `SlicerDMRI` should be required. For that issue, I will commit a change into Slicer shortly.
