### ISSUE TITLE
DWI Weighted Masking

### ISSUE THREAD

**Issue by spujol** [SlicerDMRI/SlicerDMRI#26]
The Diffusion Weighted Volume Masking is generating an error message when tested with the DWI tutorial dataset.

Input port 0 of algorithm vtkImageWeightedSum(0x10f70b440) has 0 connections but is not optional.

/Applications/Slicer.app/Contents/lib/Slicer-4.5/cli-modules/DiffusionWeightedVolumeMasking: Error parsing Diffusion information, no B0 images

Diffusion Weighted Volume Masking completed with errors

Steps to reproduce the bug:
1. Load the DWI tutorial dataset in Slicer
2. Select the module Diffusion Weighted Volume Masking
3. Set input volume --> dwi.nrrd
4. Set OutputVolume and OutputThresholdMask to 'Create New'
5.Set Otsu Threshold to 0.05
6. Uncheck 'Remove Islands'
<img width="1432" alt="dwi-mask" src="https://cloud.githubusercontent.com/assets/1847492/12651796/13ed6964-c5b6-11e5-81de-ba6ec9f9efe9.png">

**Comment by ljod** [comment]
Thank you!

I think we have seen this before specifically with the tutorial dataset. Isaiah will know.

Lauren


On Jan 28, 2016, at 11:56 AM, spujol <notifications@github.com<mailto:notifications@github.com>> wrote:


The Diffusion Weighted Volume Masking is generating an error message when tested with the DWI tutorial dataset

Input port 0 of algorithm vtkImageWeightedSum(0x10f70b440) has 0 connections but is not optional

/Applications/Slicerapp/Contents/lib/Slicer-45/cli-modules/DiffusionWeightedVolumeMasking: Error parsing Diffusion information, no B0 images

Diffusion Weighted Volume Masking completed with errors

Steps to reproduce the bug:
1 Load the DWI tutorial dataset in Slicer
2 Select the module Diffusion Weighted Volume Masking
3 Set input volume --> dwinrrd
4 Set OutputVolume and OutputThresholdMask to 'Create New'
5Set Otsu Threshold to 005
6 Uncheck 'Remove Islands'
[dwi-mask]<https://camo.githubusercontent.com/3f95c2834a5f5a6c3ddc1ca14b9192a767e3622a/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f313834373439322f31323635313739362f31336564363936342d633562362d313165352d383164652d626136656339663965666539706e67>

—
Reply to this email directly or view it on GitHub<https://github.com/SlicerDMRI/SlicerDMRI/issues/26>.



The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by ihnorton** [comment]
@spujol thanks, the issue is that the "B0" images in the tutorial dataset have a gradient magnitude exceeding the B0 tolerance. See [debug output here](https://gist.github.com/ihnorton/b059b435ff77106dae14), whereas the [tolerance is 1e-6](https://github.com/SlicerDMRI/SlicerDMRI/blob/053709c83a37409596a52ef1e0cc6c34e486be06/Modules/CLI/DiffusionWeightedVolumeMasking/DiffusionWeightedVolumeMasking.cxx#L33).

It seems that this tutorial dataset was [updated recently](http://wiki.slicer.org/slicerWiki/index.php/Special:ListFiles?limit=50&ilsearch=Dti_tutorial_data.zip&user=) , so I would like to investigate the original data to see if there was an issue in the initial conversion or possibly roundoff error in subsequent rewrites. Would it be possible to share the original DICOM images?

**Comment by spujol** [comment]
The DWI Volume masking module with this tutorial dataset was working with Slicer4.4.0.2015-05.21.

Below is the link to Slicer4.4.0.2015-05.21 if this can help:
https://www.dropbox.com/s/u9lwqu0slweyn47/Slicer-4.4.0-2015-05-21-macosx-amd64.dmg.zip?dl=0

**Comment by ihnorton** [comment]
The gradient sum for tolerance check was previously not calculated correctly, leading to bugs for some datasets. This was fixed between 4.4 and 4.5 release, see:
https://github.com/Slicer/Slicer/pull/380
http://www.na-mic.org/Bug/view.php?id=3855

> Let me know if you still need the dicom images.

Yes, please. I would prefer to investigate from the source first before considering relaxing the tolerance (which has been in place for a long time, but was applied incorrectly).

**Comment by ljod** [comment]
I agree looking at the DICOMs is an important check.

Regarding the tolerance, the threshold looks too small. For masking, any scan with b less than 10 for example would be reasonable. All we are really looking for is strong signal so even b in the low hundreds should work. Let's ask around lab about different protocols and see how often the baseline is a bit above zero.
Lauren

**Comment by ihnorton** [comment]
@spujol sent the dataset, and the conversion looks fine, the low b-values are from 3-5 (directly from the BMatrix).

Sounds like we should check the actual b-value in the masking routine rather than just the gradient magnitude, and threshold on that. And also add an option to control the threshold. This was previously not an issue because the gradient components were all rounded to zero, so we considered all images to be baseline and averaged them.

**Comment by spujol** [comment]
I ran the Diffusion Weighted Volume Masking in Slicer4.5.0-2016-02-23 nightly build with the Diffusion MRI tutorial dataset. I tried the default value (100) and max value (2147483647) of the Baseline B-Value Threshold Parameter. 
In both cases, the mask is generated correctly, which is great. 

The slider has a range of values up to the maximum values for int variables. Could the maximum value of the threshold parameter be set to the max B-value of the dataset?

**Comment by ljod** [comment]
That's a good idea. Alternatively if that can't be done for whatever reason (CLIs can't modify UI based on input) it could be set to a max that is reasonable for b values, say whatever is the max of the connectome scanner

**Comment by ihnorton** [comment]
Right, no way to make the value conditional, unfortunately. Updated in https://github.com/SlicerDMRI/SlicerDMRI/commit/0513bff9278ba999bb7a6ecb6e94f5b0c16c8eca to Connectome max b-value of 20k (per [this](http://www.humanconnectomeproject.org/wp-content/uploads/2012/06/Connectome_SNR_ISMRM.pdf)). Will bump the Slicer tag again in a couple days.
