### ISSUE TITLE
bad documentation comments in Slicer class vtkPolyDataTensorToColor

### ISSUE THREAD

**Issue by ljod** [SlicerDMRI/SlicerDMRI#35]
This class claims to "Extracts points whose scalar value satisfies threshold criterion. " 

https://www.slicer.org/doc/html/classvtkPolyDataTensorToColor.html#details

Also: I'm not sure whether any Slicer code uses this class--is there a path to move it into SlicerDMRI?

**Comment by ihnorton** [comment]
> Also: I'm not sure whether any Slicer code uses this class--is there a path to move it into SlicerDMRI?

done in
https://github.com/SlicerDMRI/SlicerDMRI/pull/57
