### ISSUE TITLE
fiber tract scalar measurements appears not to preserve full hierarchy tree structure

### ISSUE THREAD

**Issue by ljod** [SlicerDMRI/SlicerDMRI#36]
To do statistics, it's appropriate to focus on one level, like for example subdivisions of the corpus callosum. The hierarchy has a tree structure that can have several levels. However when I read the measurements file into python, the name of each measurement seems to preserve only two levels of the hierarchy it is nested inside, instead of the unique full name. Here's an example from our tests. Looks like there is a possible CC with several levels inside it, and at each level only the current level and the parent are listed. In theory I could try to reconstruct the tree structure, but it would be much better for Slicer to output the full name including parents up to the root node that is being measured. 

['Possible CC', 'Possible CC:complete CC medial and later', 'Possible CC:nonhomologue', 'complete CC medial and later:region I', 'complete CC medial and later:region II', 'complete CC medial and later:region III', 'complete CC medial and later:region V', 'complete CC medial and later:region VI', 'nonhomologue:anterior', 'nonhomologue:mid', 'nonhomologue:posterior']

**Comment by ihnorton** [comment]
I can't reproduce this, running measurements against (I believe) the same dataset.

> would be much better for Slicer to output the full name including parents up to the root node that is being measured.

Current output:

```
Possible CC:complete CC medial and later:region VI:cluster_00016  
Possible CC:complete CC medial and later:region VI:cluster_00020  
...        
Possible CC:nonhomologue:posterior:cluster_00524                  
Possible CC:nonhomologue:posterior:cluster_00533                  
Possible CC:nonhomologue:posterior:cluster_00577                  
Possible CC                                                       
Possible CC:complete CC medial and later                          
Possible CC:nonhomologue                                          
complete CC medial and later:region I                             
complete CC medial and later:region II                            
complete CC medial and later:region III                           
complete CC medial and later:region V                             
complete CC medial and later:region VI                            
nonhomologue:anterior                                             
nonhomologue:mid                                                  
nonhomologue:posterior                                            
```

Where the latter entries ("complete CC medial and later:region I", "nonhomologue:anterior", etc.) are summary statistics for each leaf in the hierarchy tree. They all match the hierarchy in the scene, up to the root `MRMLHierarchyNode` that is specified for analysis. (specifying a child leaf works fine, e.g. specifying the HierarchyNode for "Possible CC" will only print that and the nodes below it).

#37 turns off the cluster summary statistics by default so as not to confuse the WMA analysis.
