### ISSUE TITLE
nightly testing for diffusion tensor scalar measures

### ISSUE THREAD

**Issue by ljod** [SlicerDMRI/SlicerDMRI#40]
this should run the module for scalar measures and check the output is correct (has not changed from previous output). All measures should be checked (FA, eigenvalues, etc.)

this should use test data for example the helix dataset, and/or a small subset of a real dataset ( a few slices) provided by Isaiah

**Comment by ljod** [comment]
also please add a test for expected ranges for the normalized measures that should fall in the range of 0 to 1:
RelativeAnisotropy
FractionalAnisotropy
Mode 
LinearMeasure
PlanarMeasure
SphericalMeasure

**Comment by ayarmarkovich** [comment]
I have added tests for all scalar measures using Helix data-set. Created base line data-sets for all scalar measures and added image comparison to the tests.
