### ISSUE TITLE
Investigate negative eigenvalues in UKFtracto data

### ISSUE THREAD

**Issue by ihnorton** [SlicerDMRI/SlicerDMRI#42]
See #38 (also aa03f78b)

**Comment by ljod** [comment]
Assessing how rare this is:
https://github.com/SlicerDMRI/SlicerDMRI/commit/4ed8b659550e591cd77cde8406c4ff0d4cde738c

**Comment by ljod** [comment]
This is quite a rare occurrence with UKF tractography and the issue has been raised with that development team (Yogesh Rathi).
