### ISSUE TITLE
Inconsistent IJK point coordinate conversions between modules

### ISSUE THREAD

**Issue by zhangfanmark** [SlicerDMRI/SlicerDMRI#53]
Hi all,

Lauren and I just noticed that after transforming RAS point to IJK point, the[ FLOOR](https://github.com/SlicerDMRI/SlicerDMRI/blob/master/Modules/CLI/FiberBundleLabelSelect/FiberBundleLabelSelect.cxx#L185-L187) operation is used to get the integers of (i, j, k) in the FiberBundleLabelSelect module but [ROUND](https://github.com/SlicerDMRI/SlicerDMRI/blob/master/Modules/Scripted/FiberBundleToLabelMap/FiberBundleToLabelMap.py#L227) is used in the FiberBundleToLabelMap module. This could generate half voxel difference between the two modules.

**Comment by ihnorton** [comment]
Fixed by #55.
