### ISSUE TITLE
SlicerDMRI is missing in nightly build

### ISSUE THREAD

**Issue by fepegar** [SlicerDMRI/SlicerDMRI#76]
Hi all,
SlicerDMRI is missing in nightly build (Mac, r25872). Is there a way to install it by cloning the repo?

Best,
Fernando

**Comment by ihnorton** [comment]
You can get recent snapshot builds for mac and Linux here:
https://github.com/SlicerDMRI/SlicerDMRI/releases

Or try a nightly from Monday or Tuesday. Otherwise follow slicer extension
build instructions in the dev manual. I will investigate tonight.

**Comment by fepegar** [comment]
I'll do that, thank you.

**Comment by ihnorton** [comment]
Fixed in latest: http://slicer.cdash.org/index.php?project=Slicer4&date=2017-03-27&filtercount=1&showfilters=1&field1=label&compare1=63&value1=SlicerDMRI
