### ISSUE TITLE
BUG: TractographyDisplay on Slicer4.7

### ISSUE THREAD

**Issue by PrinceNgattaiLam** [SlicerDMRI/SlicerDMRI#78]
Hi, I add some issues to use the TractographyDisplay module on the latest version of Slicer4.7.0. with the ROI Selection. Indeed it was like my ROI was always empty even if there was fibers in it. Or rather than the display of fibers wasn't taking in account the ROI. As the results the Extraction and the Update were giving empty fiber bundle.
I was able to fix the issue concerning the Extraction and the Update by adding those lines of code:
`    if(producer){
      producer->Update();
      return vtkPolyData::SafeDownCast(producer->GetOutputDataObject(index));
    }else{
      return vtkPolyData::SafeDownCast(0); `
instead of
https://github.com/SlicerDMRI/SlicerDMRI/blob/master/Modules/Loadable/TractographyDisplay/MRML/vtkMRMLFiberBundleNode.cxx#L279-L280

With that I can extract and update bundles that are within my ROI. But there is still the problem of the display of fibers, to be able to see what I am about to extract. I wasn't able to find where exactly the update of the scene and the selected fibers were done. So I would really appreciate your help on that. Thanks in advance.

**Comment by ihnorton** [comment]
Hi @PrinceNgattaiLam, thanks for the suggested fix. Calling `->Update()` probably makes sense. I will test this, and investigate the other display issue.

**Comment by ihnorton** [comment]
Fixed by https://github.com/SlicerDMRI/SlicerDMRI/commit/56a031c9672f42de14ed5a5361371a65d0ba72c3
