### ISSUE TITLE
Default Tube tract slows down tract display

### ISSUE THREAD

**Issue by zhangfanmark** [SlicerDMRI/SlicerDMRI#98]
Hi!

Displaying tube makes Slicer very slow when loading whole brain tractography (I tried one with only about 10k fibers). Why did we change the default display from Line to Tube? 

Thanks!

Fan

**Comment by ihnorton** [comment]
I'm not sure if line was ever default, but I agree this is a good change. At least until tube can be equivalently fast. #99 changes the default for new nodes (existing MRML scenes will be left alone).
